#!/bin/bash
ppid=$(pidof Risstretto\ Image\ Viewer)
#You can change the "Risstretto\ Image\ Viewer" to any python3 or renamed python3 application in /usr/bin/
build="fc86f27"
if [ "$(xdotool getactivewindow getwindowname)" == "Tux Clicker Dev Build 1" ]; then
kill -CONT $ppid
exec "$0" "$@"
elif [ "$(xdotool getactivewindow getwindowname)" == "Lunar Client (1.8.9-"$build"/master)" ]; then
kill -CONT $ppid
exec "$0" "$@"
elif [ "$(xdotool getactivewindow getwindowname)" == "Lunar Client (1.16.5-"$build"/master)" ]; then
kill -CONT $ppid
exec "$0" "$@"
elif [ "$(xdotool getactivewindow getwindowname)" == "Lunar Client (1.12.2-"$build"/master)" ]; then
kill -CONT $ppid
exec "$0" "$@"
elif [ "$(xdotool getactivewindow getwindowname)" == "Lunar Client (1.7.10-"$build"/master)" ]; then
kill -CONT $ppid
exec "$0" "$@"
elif [ "$(xdotool getactivewindow getwindowname)" == "Lunar Client (1.17.1-"$build"/master)" ]; then
kill -CONT $ppid
exec "$0" "$@"
elif [ "$(xdotool getactivewindow getwindowname)" == "Lunar Client (1.18.1-"$build"/master)" ]; then
kill -CONT $ppid
exec "$0" "$@"
else
kill -STOP $ppid
exec "$0" "$@"
fi
fi
